Repository polysemy-research/polysemy, pull requests merged in 2020-07, with the labels that each got.

#364 Update README
  README.md
Labels: documentation

#369 raise2Under and raise3Under
  src/Polysemy.hs
  src/Polysemy/Internal.hs
Labels: enhancement

#370 Add 'Raise' and 'Subsume'
  src/Polysemy.hs
  src/Polysemy/Internal.hs
Labels: enhancement, polish
